export const APPLICATION_STATES = [
  "DISCOVERED",
  "DUPLICATE_CHECK",
  "ELIGIBILITY_CHECK",
  "FILTERED_OUT",
  "QUEUED",
  "MATERIALS_GENERATING",
  "RESUME_DOWNLOADED",
  "COVER_LETTER_REQUIRED",
  "COVER_LETTER_DOWNLOADED",
  "APPLICATION_OPENING",
  "ATS_DETECTION",
  "APPLICATION_INSPECTION",
  "JOBRIGHT_AUTOFILL_RUNNING",
  "JOBRIGHT_AUTOFILL_VERIFICATION",
  "FORM_RESETTING",
  "NATIVE_AUTOFILL_RUNNING",
  "FIELD_VERIFICATION",
  "ESSAY_REQUIRED",
  "AUTH_REQUIRED",
  "CAPTCHA_REQUIRED",
  "AMBIGUOUS_FIELD",
  "UNSUPPORTED_ATS",
  "READY_TO_SUBMIT",
  "SUBMITTING",
  "SUBMITTED",
  "SUBMISSION_VERIFICATION_FAILED",
  "CONTACTS_EXTRACTING",
  "CONTACTS_EXTRACTED",
  "LINKEDIN_ENRICHING",
  "LINKEDIN_ENRICHED",
  "EMAIL_GENERATING",
  "EMAIL_GENERATED",
  "DRAFT_CREATING",
  "DRAFT_CREATED",
  "COMPLETED",
  "FAILED_RETRYABLE",
  "FAILED_FINAL",
] as const;

export type ApplicationState = (typeof APPLICATION_STATES)[number];

export const APPLICATION_ROUTES = [
  "AUTO_SUBMIT",
  "ESSAY_REQUIRED",
  "AUTH_REQUIRED",
  "CAPTCHA_REQUIRED",
  "UNSUPPORTED_ATS",
  "AMBIGUOUS_FIELD",
  "INELIGIBLE",
  "DUPLICATE",
  "FAILED_RETRYABLE",
  "FAILED_FINAL",
] as const;

export type ApplicationRoute = (typeof APPLICATION_ROUTES)[number];

const ALLOWED: Partial<Record<ApplicationState, readonly ApplicationState[]>> = {
  DISCOVERED: ["DUPLICATE_CHECK", "FAILED_RETRYABLE", "FAILED_FINAL"],
  DUPLICATE_CHECK: ["ELIGIBILITY_CHECK", "FILTERED_OUT", "FAILED_FINAL"],
  ELIGIBILITY_CHECK: ["QUEUED", "FILTERED_OUT", "FAILED_FINAL"],
  FILTERED_OUT: [],
  QUEUED: ["MATERIALS_GENERATING", "FAILED_RETRYABLE", "FAILED_FINAL"],
  MATERIALS_GENERATING: [
    "RESUME_DOWNLOADED",
    "FAILED_RETRYABLE",
    "FAILED_FINAL",
  ],
  RESUME_DOWNLOADED: [
    "COVER_LETTER_REQUIRED",
    "APPLICATION_OPENING",
    "FAILED_RETRYABLE",
    "FAILED_FINAL",
  ],
  COVER_LETTER_REQUIRED: [
    "COVER_LETTER_DOWNLOADED",
    "FAILED_RETRYABLE",
    "FAILED_FINAL",
  ],
  COVER_LETTER_DOWNLOADED: [
    "APPLICATION_OPENING",
    "FAILED_RETRYABLE",
    "FAILED_FINAL",
  ],
  APPLICATION_OPENING: [
    "ATS_DETECTION",
    "AUTH_REQUIRED",
    "CAPTCHA_REQUIRED",
    "UNSUPPORTED_ATS",
    "FAILED_RETRYABLE",
    "FAILED_FINAL",
  ],
  ATS_DETECTION: [
    "APPLICATION_INSPECTION",
    "UNSUPPORTED_ATS",
    "FAILED_RETRYABLE",
    "FAILED_FINAL",
  ],
  APPLICATION_INSPECTION: [
    "JOBRIGHT_AUTOFILL_RUNNING",
    "NATIVE_AUTOFILL_RUNNING",
    "ESSAY_REQUIRED",
    "AMBIGUOUS_FIELD",
    "AUTH_REQUIRED",
    "CAPTCHA_REQUIRED",
    "UNSUPPORTED_ATS",
    "FAILED_RETRYABLE",
    "FAILED_FINAL",
  ],
  JOBRIGHT_AUTOFILL_RUNNING: [
    "JOBRIGHT_AUTOFILL_VERIFICATION",
    "FAILED_RETRYABLE",
    "FAILED_FINAL",
  ],
  JOBRIGHT_AUTOFILL_VERIFICATION: [
    "FORM_RESETTING",
    "FIELD_VERIFICATION",
    "NATIVE_AUTOFILL_RUNNING",
    "ESSAY_REQUIRED",
    "AMBIGUOUS_FIELD",
    "FAILED_RETRYABLE",
    "FAILED_FINAL",
  ],
  FORM_RESETTING: [
    "NATIVE_AUTOFILL_RUNNING",
    "FAILED_RETRYABLE",
    "FAILED_FINAL",
  ],
  NATIVE_AUTOFILL_RUNNING: [
    "FIELD_VERIFICATION",
    "ESSAY_REQUIRED",
    "AMBIGUOUS_FIELD",
    "FAILED_RETRYABLE",
    "FAILED_FINAL",
  ],
  FIELD_VERIFICATION: [
    "READY_TO_SUBMIT",
    "ESSAY_REQUIRED",
    "AMBIGUOUS_FIELD",
    "FAILED_RETRYABLE",
    "FAILED_FINAL",
  ],
  ESSAY_REQUIRED: [
    "FIELD_VERIFICATION",
    "READY_TO_SUBMIT",
    "APPLICATION_INSPECTION",
    "NATIVE_AUTOFILL_RUNNING",
    "FAILED_RETRYABLE",
    "FAILED_FINAL",
  ],
  AUTH_REQUIRED: ["APPLICATION_OPENING", "FAILED_FINAL"],
  CAPTCHA_REQUIRED: ["FAILED_FINAL"],
  AMBIGUOUS_FIELD: ["FIELD_VERIFICATION", "FAILED_FINAL"],
  UNSUPPORTED_ATS: ["FAILED_FINAL"],
  READY_TO_SUBMIT: ["SUBMITTING", "FAILED_RETRYABLE", "FAILED_FINAL"],
  SUBMITTING: [
    "SUBMITTED",
    "SUBMISSION_VERIFICATION_FAILED",
    "FAILED_RETRYABLE",
    "FAILED_FINAL",
  ],
  SUBMITTED: [
    "CONTACTS_EXTRACTING",
    "COMPLETED",
    "FAILED_RETRYABLE",
    "FAILED_FINAL",
  ],
  // Operator resolution of an uncertain submission (review:resolve):
  // → SUBMITTED when the receipt is confirmed to exist;
  // → FAILED_RETRYABLE when confirmed nothing was submitted (explicit re-queue).
  SUBMISSION_VERIFICATION_FAILED: [
    "SUBMITTED",
    "FAILED_RETRYABLE",
    "FAILED_FINAL",
  ],
  CONTACTS_EXTRACTING: [
    "CONTACTS_EXTRACTED",
    "FAILED_RETRYABLE",
    "COMPLETED",
  ],
  CONTACTS_EXTRACTED: ["LINKEDIN_ENRICHING", "EMAIL_GENERATING", "COMPLETED"],
  LINKEDIN_ENRICHING: ["LINKEDIN_ENRICHED", "EMAIL_GENERATING", "COMPLETED"],
  LINKEDIN_ENRICHED: ["EMAIL_GENERATING", "COMPLETED"],
  EMAIL_GENERATING: ["EMAIL_GENERATED", "COMPLETED", "FAILED_RETRYABLE"],
  EMAIL_GENERATED: ["DRAFT_CREATING", "COMPLETED"],
  DRAFT_CREATING: ["DRAFT_CREATED", "FAILED_RETRYABLE", "COMPLETED"],
  DRAFT_CREATED: ["COMPLETED"],
  COMPLETED: [],
  FAILED_RETRYABLE: [
    "QUEUED",
    "MATERIALS_GENERATING",
    "APPLICATION_OPENING",
    "FAILED_FINAL",
  ],
  FAILED_FINAL: [],
};

export function canTransition(
  from: ApplicationState,
  to: ApplicationState,
): boolean {
  if (from === to) return true;
  const allowed = ALLOWED[from];
  return allowed?.includes(to) ?? false;
}

export function assertTransition(
  from: ApplicationState,
  to: ApplicationState,
): void {
  if (!canTransition(from, to)) {
    throw new Error(`Invalid state transition: ${from} -> ${to}`);
  }
}
